// Auto-generated from calc.xlsx. Do not edit manually.
export const dataset = {
  "meta": {
    "source": "calc.xlsx",
    "generatedAt": 1763109363.7102587
  },
  "aspectRatios": [
    {
      "id": "item",
      "label": "нестандартное, горизонтально вытянутое",
      "ratioMax": 2.1,
      "width": null,
      "height": null
    },
    {
      "id": "2-1",
      "label": "приблизительно 2:1",
      "ratioMax": 2.0001,
      "width": 2.0001,
      "height": 1.0
    },
    {
      "id": "2-1",
      "label": "ровно 2:1",
      "ratioMax": 2.0,
      "width": 2.0,
      "height": 1.0
    },
    {
      "id": "2-1",
      "label": "приблизительно 2:1",
      "ratioMax": 1.8888944444444444,
      "width": null,
      "height": null
    },
    {
      "id": "16-9",
      "label": "приблизительно 16:9",
      "ratioMax": 1.7777888888888889,
      "width": 16.0001,
      "height": 9.0
    },
    {
      "id": "16-9",
      "label": "ровно 16:9",
      "ratioMax": 1.7777777777777777,
      "width": 16.0,
      "height": 9.0
    },
    {
      "id": "16-9",
      "label": "приблизительно 16:9",
      "ratioMax": 1.688893888888889,
      "width": null,
      "height": null
    },
    {
      "id": "16-10",
      "label": "приблизительно 16:10",
      "ratioMax": 1.60001,
      "width": 16.0001,
      "height": 10.0
    },
    {
      "id": "16-10",
      "label": "ровно 16:10",
      "ratioMax": 1.6,
      "width": 16.0,
      "height": 10.0
    },
    {
      "id": "16-10",
      "label": "приблизительно 16:10",
      "ratioMax": 1.5500250000000002,
      "width": null,
      "height": null
    },
    {
      "id": "3-2",
      "label": "приблизительно 3:2",
      "ratioMax": 1.50005,
      "width": 3.0001,
      "height": 2.0
    },
    {
      "id": "3-2",
      "label": "ровно 3:2",
      "ratioMax": 1.5,
      "width": 3.0,
      "height": 2.0
    },
    {
      "id": "3-2",
      "label": "приблизительно 3:2",
      "ratioMax": 1.4166833333333333,
      "width": null,
      "height": null
    },
    {
      "id": "4-3",
      "label": "приблизительно 4:3 ",
      "ratioMax": 1.3333666666666666,
      "width": 4.0001,
      "height": 3.0
    },
    {
      "id": "4-3",
      "label": "ровно 4:3 ",
      "ratioMax": 1.3333333333333333,
      "width": 4.0,
      "height": 3.0
    },
    {
      "id": "4-3",
      "label": "приблизительно 4:3 ",
      "ratioMax": 1.1666666666666667,
      "width": 3.5,
      "height": 3.0
    },
    {
      "id": "item",
      "label": "нестандартное, почти квадратное",
      "ratioMax": 1.0001,
      "width": null,
      "height": null
    },
    {
      "id": "item",
      "label": "нестандартное, квадратное",
      "ratioMax": 1.0,
      "width": null,
      "height": null
    },
    {
      "id": "item",
      "label": "нестандартное, почти квадратное",
      "ratioMax": 0.85,
      "width": null,
      "height": null
    },
    {
      "id": "item",
      "label": "нестандартное, вертикально вытянутое",
      "ratioMax": 0.0,
      "width": null,
      "height": null
    }
  ],
  "cabinets": [
    {
      "id": "qiangli-caci-320160",
      "manufacturer": "Qiangli",
      "sku": "CACI-320160",
      "name": "Кабинет алюминиевый 320x160-C indoor, 320*160*45 мм, перед обслуж; только на магнитах 12x8; без коммутации",
      "execution": "Внутренний",
      "service": "Фронтальное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 320.0,
      "cabinetHeightMm": 160.0,
      "modulesWide": 1.0,
      "modulesTall": 1.0,
      "weightKg": 1.0,
      "priceUsd": 25.0,
      "priceRub": null
    },
    {
      "id": "qiangli-caci-640480",
      "manufacturer": "Qiangli",
      "sku": "CACI-640480",
      "name": "Кабинет алюминиевый 640x480-C indoor, 640*480*45 мм, перед обслуж; только на магнитах 12x8; без коммутации",
      "execution": "Внутренний",
      "service": "Фронтальное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 640.0,
      "cabinetHeightMm": 480.0,
      "modulesWide": 2.0,
      "modulesTall": 3.0,
      "weightKg": 3.25,
      "priceUsd": 45.0,
      "priceRub": null
    },
    {
      "id": "qiangli-cadm-500500",
      "manufacturer": "Qiangli",
      "sku": "CADM-500500",
      "name": "Кабинет алюминиевый 500х500 с коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит, карту. 500*500*70мм",
      "execution": "Внутренний",
      "service": "Фронтальное",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 500.0,
      "cabinetHeightMm": 500.0,
      "modulesWide": 2.0,
      "modulesTall": 2.0,
      "weightKg": 3.8,
      "priceUsd": 61.0,
      "priceRub": null
    },
    {
      "id": "qiangli-cadm-500500",
      "manufacturer": "Qiangli",
      "sku": "CADM-500500",
      "name": "Кабинет алюминиевый 500х500 с коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит, карту. 500*500*70мм",
      "execution": "Внутренний",
      "service": "Тыльное",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 500.0,
      "cabinetHeightMm": 500.0,
      "modulesWide": 2.0,
      "modulesTall": 2.0,
      "weightKg": 3.8,
      "priceUsd": 61.0,
      "priceRub": null
    },
    {
      "id": "qiangli-cadm-500500",
      "manufacturer": "Qiangli",
      "sku": "CADM-500500",
      "name": "Кабинет алюминиевый 500х500 с коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит, карту. 500*500*70мм",
      "execution": "Уличный",
      "service": "Фронтальное",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 500.0,
      "cabinetHeightMm": 500.0,
      "modulesWide": 2.0,
      "modulesTall": 2.0,
      "weightKg": 3.8,
      "priceUsd": 61.0,
      "priceRub": null
    },
    {
      "id": "qiangli-cadm-500500",
      "manufacturer": "Qiangli",
      "sku": "CADM-500500",
      "name": "Кабинет алюминиевый 500х500 с коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит, карту. 500*500*70мм",
      "execution": "Уличный",
      "service": "Тыльное",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 500.0,
      "cabinetHeightMm": 500.0,
      "modulesWide": 2.0,
      "modulesTall": 2.0,
      "weightKg": 3.8,
      "priceUsd": 61.0,
      "priceRub": null
    },
    {
      "id": "qiangli-cadm-5001000",
      "manufacturer": "Qiangli",
      "sku": "CADM-5001000",
      "name": "Кабинет алюминиевый 500х1000 с коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит, карту. 500*1000*70мм",
      "execution": "Внутренний",
      "service": "Фронтальное",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 500.0,
      "cabinetHeightMm": 1000.0,
      "modulesWide": 2.0,
      "modulesTall": 4.0,
      "weightKg": 6.1,
      "priceUsd": 88.0,
      "priceRub": null
    },
    {
      "id": "qiangli-cadm-5001000",
      "manufacturer": "Qiangli",
      "sku": "CADM-5001000",
      "name": "Кабинет алюминиевый 500х1000 с коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит, карту. 500*1000*70мм",
      "execution": "Внутренний",
      "service": "Тыльное",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 500.0,
      "cabinetHeightMm": 1000.0,
      "modulesWide": 2.0,
      "modulesTall": 4.0,
      "weightKg": 6.1,
      "priceUsd": 88.0,
      "priceRub": null
    },
    {
      "id": "qiangli-cadm-5001000",
      "manufacturer": "Qiangli",
      "sku": "CADM-5001000",
      "name": "Кабинет алюминиевый 500х1000 с коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит, карту. 500*1000*70мм",
      "execution": "Уличный",
      "service": "Фронтальное",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 500.0,
      "cabinetHeightMm": 1000.0,
      "modulesWide": 2.0,
      "modulesTall": 4.0,
      "weightKg": 6.1,
      "priceUsd": 88.0,
      "priceRub": null
    },
    {
      "id": "qiangli-cadm-5001000",
      "manufacturer": "Qiangli",
      "sku": "CADM-5001000",
      "name": "Кабинет алюминиевый 500х1000 с коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит, карту. 500*1000*70мм",
      "execution": "Уличный",
      "service": "Тыльное",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 500.0,
      "cabinetHeightMm": 1000.0,
      "modulesWide": 2.0,
      "modulesTall": 4.0,
      "weightKg": 6.1,
      "priceUsd": 88.0,
      "priceRub": null
    },
    {
      "id": "qiangli-ca-576576",
      "manufacturer": "Qiangli",
      "sku": "CA-576576",
      "name": "Кабинет алюминиевый 576х576 с коммутацией, Indoor/Outdoor, в компл пластина под блок пит,карту. 576*576*70мм",
      "execution": "Внутренний",
      "service": "Тыльное",
      "moduleWidthMm": 192.0,
      "cabinetWidthMm": 576.0,
      "cabinetHeightMm": 576.0,
      "modulesWide": 3.0,
      "modulesTall": 3.0,
      "weightKg": 6.1,
      "priceUsd": 86.0,
      "priceRub": null
    },
    {
      "id": "qiangli-ca-576576",
      "manufacturer": "Qiangli",
      "sku": "CA-576576",
      "name": "Кабинет алюминиевый 576х576 с коммутацией, Indoor/Outdoor, в компл пластина под блок пит,карту. 576*576*70мм",
      "execution": "Уличный",
      "service": "Тыльное",
      "moduleWidthMm": 192.0,
      "cabinetWidthMm": 576.0,
      "cabinetHeightMm": 576.0,
      "modulesWide": 3.0,
      "modulesTall": 3.0,
      "weightKg": 6.1,
      "priceUsd": 86.0,
      "priceRub": null
    },
    {
      "id": "qiangli-ca-640640",
      "manufacturer": "Qiangli",
      "sku": "CA-640640",
      "name": "Кабинет алюминиевый 640х640 c коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит,карту. 640*640*70мм",
      "execution": "Внутренний",
      "service": "Тыльное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 640.0,
      "cabinetHeightMm": 640.0,
      "modulesWide": 2.0,
      "modulesTall": 4.0,
      "weightKg": 5.7,
      "priceUsd": 82.5,
      "priceRub": null
    },
    {
      "id": "qiangli-ca-640640",
      "manufacturer": "Qiangli",
      "sku": "CA-640640",
      "name": "Кабинет алюминиевый 640х640 c коммутацией, Indoor/Outdoor, в комплекте пластина под блок пит,карту. 640*640*70мм",
      "execution": "Уличный",
      "service": "Тыльное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 640.0,
      "cabinetHeightMm": 640.0,
      "modulesWide": 2.0,
      "modulesTall": 4.0,
      "weightKg": 5.7,
      "priceUsd": 82.5,
      "priceRub": null
    },
    {
      "id": "qiangli-caci-640640",
      "manufacturer": "Qiangli",
      "sku": "CACI-640640",
      "name": "Кабинет алюминиевый 640х640-C indoor, 640*640*45 мм, перед обслуж; только на магнитах 12x8; без коммутации",
      "execution": "Внутренний",
      "service": "Фронтальное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 640.0,
      "cabinetHeightMm": 640.0,
      "modulesWide": 2.0,
      "modulesTall": 4.0,
      "weightKg": 5.5,
      "priceUsd": 61.0,
      "priceRub": null
    },
    {
      "id": "qiangli-caoi-960960",
      "manufacturer": "Qiangli",
      "sku": "CAOI-960960",
      "name": "Кабинет алюминиевый 960х960 indoor с коммутацией. Подходит только для интерьерных модулей 960*960*85,8мм",
      "execution": "Внутренний",
      "service": "Тыльное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 960.0,
      "cabinetHeightMm": 960.0,
      "modulesWide": 3.0,
      "modulesTall": 6.0,
      "weightKg": 14.0,
      "priceUsd": 165.0,
      "priceRub": null
    },
    {
      "id": "qiangli-caoo-960960",
      "manufacturer": "Qiangli",
      "sku": "CAOO-960960",
      "name": "Кабинет алюминиевый 960х960 outdoor с коммутацией. Подходит только для уличных модулей 960*960*85,8мм",
      "execution": "Уличный",
      "service": "Тыльное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 960.0,
      "cabinetHeightMm": 960.0,
      "modulesWide": 3.0,
      "modulesTall": 6.0,
      "weightKg": 14.0,
      "priceUsd": 165.0,
      "priceRub": null
    },
    {
      "id": "640-640-outdoor",
      "manufacturer": "Политех",
      "sku": "640*640 Outdoor",
      "name": "Кабинет стальной, 640*640 Outdoor, фронтальное обслуживание (уточнить вес кабинета, расчет на 10 кг)",
      "execution": "Уличный",
      "service": "Фронтальное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 640.0,
      "cabinetHeightMm": 640.0,
      "modulesWide": 2.0,
      "modulesTall": 4.0,
      "weightKg": 10.0,
      "priceUsd": 76.0,
      "priceRub": 6300.0
    },
    {
      "id": "640-480-outdoor",
      "manufacturer": "Политех",
      "sku": "640*480 Outdoor",
      "name": "Кабинет стальной, 640*480 Outdoor, фронтальное обслуживание (уточнить вес кабинета, расчет на 8 кг)",
      "execution": "Уличный",
      "service": "Фронтальное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 640.0,
      "cabinetHeightMm": 480.0,
      "modulesWide": 2.0,
      "modulesTall": 3.0,
      "weightKg": 8.0,
      "priceUsd": 71.0,
      "priceRub": 5900.0
    },
    {
      "id": "960-960-outdoor",
      "manufacturer": "Политех",
      "sku": "960*960 Outdoor",
      "name": "Кабинет стальной 960х960x130 мм уличный (фронтальный), IP54/IP65 (задняя/лицевая сторона)",
      "execution": "Уличный",
      "service": "Фронтальное",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 960.0,
      "cabinetHeightMm": 960.0,
      "modulesWide": 3.0,
      "modulesTall": 6.0,
      "weightKg": 15.5,
      "priceUsd": 95.0,
      "priceRub": 7900.0
    },
    {
      "id": "novastar-mrv-208",
      "manufacturer": "",
      "sku": null,
      "name": "Контроллер Novastar MRV 208",
      "execution": "Принимающая карта",
      "service": 0,
      "moduleWidthMm": null,
      "cabinetWidthMm": 256.0,
      "cabinetHeightMm": 256.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.075,
      "priceUsd": 15.0,
      "priceRub": null
    },
    {
      "id": "novastar-mrv-416",
      "manufacturer": "",
      "sku": null,
      "name": "Контроллер Novastar MRV 416",
      "execution": "Принимающая карта",
      "service": 0,
      "moduleWidthMm": null,
      "cabinetWidthMm": 512.0,
      "cabinetHeightMm": 384.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.125,
      "priceUsd": 18.9,
      "priceRub": null
    },
    {
      "id": "novastar-mrv-412",
      "manufacturer": "",
      "sku": null,
      "name": "Контроллер Novastar MRV 412",
      "execution": "Принимающая карта",
      "service": 0,
      "moduleWidthMm": null,
      "cabinetWidthMm": 512.0,
      "cabinetHeightMm": 512.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.125,
      "priceUsd": 18.5,
      "priceRub": null
    },
    {
      "id": "novastar-a5s-plus-1",
      "manufacturer": "",
      "sku": null,
      "name": "Контроллер Novastar A5s Plus",
      "execution": "Контроллер",
      "service": 1,
      "moduleWidthMm": null,
      "cabinetWidthMm": 512.0,
      "cabinetHeightMm": 384.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.366,
      "priceUsd": 17.0,
      "priceRub": null
    },
    {
      "id": "novastar-a10s-plus-1",
      "manufacturer": "",
      "sku": null,
      "name": "Контроллер Novastar A10s Plus",
      "execution": "Контроллер",
      "service": 1,
      "moduleWidthMm": null,
      "cabinetWidthMm": 512.0,
      "cabinetHeightMm": 512.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.366,
      "priceUsd": 46.0,
      "priceRub": null
    },
    {
      "id": "item",
      "manufacturer": "",
      "sku": null,
      "name": "Хаб",
      "execution": "Тип",
      "service": null,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": null,
      "priceRub": null
    },
    {
      "id": "hub-320-axs",
      "manufacturer": "",
      "sku": null,
      "name": "Плата HUB 320-AXS",
      "execution": "Хаб",
      "service": null,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 15.0,
      "priceRub": null
    },
    {
      "id": "item",
      "manufacturer": "",
      "sku": null,
      "name": "Процессор/контроллер",
      "execution": "Тип",
      "service": "Масштабирование",
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": null,
      "priceRub": null
    },
    {
      "id": "novastar-mctrl-300",
      "manufacturer": "",
      "sku": null,
      "name": "Novastar MCTRL 300",
      "execution": "Контроллер",
      "service": "Без масштабирования",
      "moduleWidthMm": 650000.0,
      "cabinetWidthMm": 3840.0,
      "cabinetHeightMm": 3840.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 161.0,
      "priceRub": null
    },
    {
      "id": "novastar-mctrl-600",
      "manufacturer": "",
      "sku": null,
      "name": "Novastar MCTRL 600",
      "execution": "Контроллер",
      "service": "Без масштабирования",
      "moduleWidthMm": 650000.0,
      "cabinetWidthMm": 3840.0,
      "cabinetHeightMm": 3840.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 294.0,
      "priceRub": null
    },
    {
      "id": "novastar-m-trl-700",
      "manufacturer": "",
      "sku": null,
      "name": "Novastar MСTRL 700",
      "execution": "Контроллер",
      "service": "Без масштабирования",
      "moduleWidthMm": 650000.0,
      "cabinetWidthMm": 3840.0,
      "cabinetHeightMm": 3840.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 307.0,
      "priceRub": null
    },
    {
      "id": "novastar-vx400s-n",
      "manufacturer": "",
      "sku": null,
      "name": "Novastar VX400S-N",
      "execution": "Видеопроцессор",
      "service": "С масштабированием",
      "moduleWidthMm": 650000.0,
      "cabinetWidthMm": 10240.0,
      "cabinetHeightMm": 8192.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 520.0,
      "priceRub": null
    },
    {
      "id": "novastar-vx400",
      "manufacturer": "",
      "sku": null,
      "name": "Novastar VX400",
      "execution": "Видеопроцессор",
      "service": "С масштабированием",
      "moduleWidthMm": 650000.0,
      "cabinetWidthMm": 10240.0,
      "cabinetHeightMm": 8192.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 926.0,
      "priceRub": null
    },
    {
      "id": "novastar-vx600",
      "manufacturer": "",
      "sku": null,
      "name": "Novastar VX600",
      "execution": "Видеопроцессор",
      "service": "С масштабированием",
      "moduleWidthMm": 650000.0,
      "cabinetWidthMm": 10240.0,
      "cabinetHeightMm": 8192.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 1100.0,
      "priceRub": null
    },
    {
      "id": "novastar-vx1000",
      "manufacturer": "",
      "sku": null,
      "name": "Novastar VX1000",
      "execution": "Видеопроцессор",
      "service": "С масштабированием",
      "moduleWidthMm": 650000.0,
      "cabinetWidthMm": 10240.0,
      "cabinetHeightMm": 8192.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 1590.0,
      "priceRub": null
    },
    {
      "id": "novastar-vx16s",
      "manufacturer": "",
      "sku": null,
      "name": "Novastar VX16S",
      "execution": "Видеопроцессор",
      "service": "С масштабированием",
      "moduleWidthMm": 650000.0,
      "cabinetWidthMm": 16384.0,
      "cabinetHeightMm": 8192.0,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 2920.0,
      "priceRub": null
    },
    {
      "id": "item",
      "manufacturer": "",
      "sku": null,
      "name": "Блоки питания",
      "execution": "Мощность, Вт",
      "service": "Сила тока, А",
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": null,
      "priceRub": null
    },
    {
      "id": "a-200af-4-5-slim-200-40",
      "manufacturer": "",
      "sku": null,
      "name": "Блок питания A-200AF 4,5 slim",
      "execution": 200,
      "service": 40,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.56,
      "priceUsd": 8.0,
      "priceRub": null
    },
    {
      "id": "a-300fay-4-5-300-60",
      "manufacturer": "",
      "sku": null,
      "name": "Блок питания A-300FAY 4,5",
      "execution": 300,
      "service": 60,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.56,
      "priceUsd": 15.4,
      "priceRub": null
    },
    {
      "id": "a-350a-4-5-slim-350-70",
      "manufacturer": "",
      "sku": null,
      "name": "Блок питания A-350AК-4,5 slim",
      "execution": 350,
      "service": 70,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.56,
      "priceUsd": 16.2,
      "priceRub": null
    },
    {
      "id": "a-400ak-4-5-slim-400-80",
      "manufacturer": "",
      "sku": null,
      "name": "Блок питания A-400AK 4,5 Slim",
      "execution": 400,
      "service": 80,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": 0.56,
      "priceUsd": 17.3,
      "priceRub": null
    },
    {
      "id": "item",
      "manufacturer": "",
      "sku": null,
      "name": "Комплектующие",
      "execution": "Тип",
      "service": "Обслуживание",
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": null,
      "priceRub": null
    },
    {
      "id": "4-12",
      "manufacturer": "",
      "sku": null,
      "name": "Винт М4*12",
      "execution": "Крепеж",
      "service": "Тыльное",
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 0.05,
      "priceRub": null
    },
    {
      "id": "12-8-1-2",
      "manufacturer": "",
      "sku": null,
      "name": "Магнит 12*8*1,2",
      "execution": "Крепеж",
      "service": "Фронтальное",
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 0.08,
      "priceRub": null
    },
    {
      "id": "16-pin",
      "manufacturer": "",
      "sku": null,
      "name": "Коннектор 16 PIN",
      "execution": "Коннектор",
      "service": null,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 0.09,
      "priceRub": null
    },
    {
      "id": "26-pin",
      "manufacturer": "",
      "sku": null,
      "name": "Коннектор 26 PIN",
      "execution": "Коннектор",
      "service": null,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 0.18,
      "priceRub": null
    },
    {
      "id": "16-pin-75",
      "manufacturer": "",
      "sku": null,
      "name": "Шлейф бухта 16 PIN, 75 м",
      "execution": "Шлейф",
      "service": null,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 25.0,
      "priceRub": null
    },
    {
      "id": "26-pin-75",
      "manufacturer": "",
      "sku": null,
      "name": "Шлейф бухта 26 PIN, 75 м",
      "execution": "Шлейф",
      "service": null,
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": 50.0,
      "priceRub": null
    },
    {
      "id": "item",
      "manufacturer": "Производитель",
      "sku": "Артикул",
      "name": "Модуль",
      "execution": "Исполнение",
      "service": "Технология",
      "moduleWidthMm": null,
      "cabinetWidthMm": null,
      "cabinetHeightMm": null,
      "modulesWide": null,
      "modulesTall": null,
      "weightKg": null,
      "priceUsd": null,
      "priceRub": null
    },
    {
      "id": "qiangli-q0-8-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q0,8-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 360.0,
      "cabinetHeightMm": 180.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.5,
      "priceUsd": 815.0000000000001,
      "priceRub": null
    },
    {
      "id": "qiangli-q1-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q1-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 320.0,
      "cabinetHeightMm": 160.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.5,
      "priceUsd": 450.0,
      "priceRub": null
    },
    {
      "id": "qiangli-q1-25-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q1,25-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 256.0,
      "cabinetHeightMm": 128.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.52,
      "priceUsd": 70.0,
      "priceRub": null
    },
    {
      "id": "qiangli-q1-37-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q1,37-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 232.0,
      "cabinetHeightMm": 116.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.47,
      "priceUsd": 81.0,
      "priceRub": null
    },
    {
      "id": "qiangli-q1-53-rgb-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q1,53-RGB (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 208.0,
      "cabinetHeightMm": 104.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.47,
      "priceUsd": 41.8,
      "priceRub": null
    },
    {
      "id": "qiangli-q1-66-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q1,66-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 192.0,
      "cabinetHeightMm": 96.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.4,
      "priceUsd": 42.2,
      "priceRub": null
    },
    {
      "id": "qiangli-q1-86-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q1,86-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 172.0,
      "cabinetHeightMm": 86.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.37,
      "priceUsd": 26.8,
      "priceRub": null
    },
    {
      "id": "qiangli-q1-86-eco-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q1,86-ECO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 172.0,
      "cabinetHeightMm": 86.0,
      "modulesWide": 1920.0,
      "modulesTall": 12.0,
      "weightKg": 0.37,
      "priceUsd": 25.2,
      "priceRub": null
    },
    {
      "id": "qiangli-q2-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q2-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 160.0,
      "cabinetHeightMm": 80.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.37,
      "priceUsd": 23.8,
      "priceRub": null
    },
    {
      "id": "qiangli-q2-eco-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q2-ECO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 160.0,
      "cabinetHeightMm": 80.0,
      "modulesWide": 1920.0,
      "modulesTall": 12.0,
      "weightKg": 0.37,
      "priceUsd": 22.25,
      "priceRub": null
    },
    {
      "id": "qiangli-q2-5-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q2,5-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 128.0,
      "cabinetHeightMm": 64.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.37,
      "priceUsd": 17.15,
      "priceRub": null
    },
    {
      "id": "qiangli-q2-5-eco-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q2,5-ECO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 128.0,
      "cabinetHeightMm": 64.0,
      "modulesWide": 1920.0,
      "modulesTall": 12.0,
      "weightKg": 0.37,
      "priceUsd": 15.3,
      "priceRub": null
    },
    {
      "id": "qiangli-smdmi-q26250250-smd",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "Светодиодный модуль QIANGLI, DM2,6 (250*250) 6000 hz,indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 250.0,
      "cabinetWidthMm": 96.0,
      "cabinetHeightMm": 96.0,
      "modulesWide": 6000.0,
      "modulesTall": 10.0,
      "weightKg": 0.5,
      "priceUsd": 25.2,
      "priceRub": null
    },
    {
      "id": "qiangli-q3-pro-192-192-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q3-PRO (192*192),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 192.0,
      "cabinetWidthMm": 64.0,
      "cabinetHeightMm": 64.0,
      "modulesWide": 3840.0,
      "modulesTall": 9.0,
      "weightKg": 0.28,
      "priceUsd": 12.4,
      "priceRub": null
    },
    {
      "id": "qiangli-q3-eco-192-192-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q3-ECO (192*192),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 192.0,
      "cabinetWidthMm": 64.0,
      "cabinetHeightMm": 64.0,
      "modulesWide": 1920.0,
      "modulesTall": 9.0,
      "weightKg": 0.28,
      "priceUsd": 10.2,
      "priceRub": null
    },
    {
      "id": "qiangli-q3-07-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q3,07-PRO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 104.0,
      "cabinetHeightMm": 52.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.32,
      "priceUsd": 13.5,
      "priceRub": null
    },
    {
      "id": "qiangli-q3-07-eco-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q3,07-ECO (320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 104.0,
      "cabinetHeightMm": 52.0,
      "modulesWide": 1920.0,
      "modulesTall": 12.0,
      "weightKg": 0.32,
      "priceUsd": 12.3,
      "priceRub": null
    },
    {
      "id": "qiangli-q4-pro-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q4-PRO(320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 80.0,
      "cabinetHeightMm": 40.0,
      "modulesWide": 3840.0,
      "modulesTall": 12.0,
      "weightKg": 0.35,
      "priceUsd": 10.9,
      "priceRub": null
    },
    {
      "id": "qiangli-q4-eco-320-160-indoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q4-ECO(320*160),indoor",
      "execution": "Внутренний",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 80.0,
      "cabinetHeightMm": 40.0,
      "modulesWide": 1920.0,
      "modulesTall": 12.0,
      "weightKg": 0.35,
      "priceUsd": 9.9,
      "priceRub": null
    },
    {
      "id": "qiangli-q2-5-pro-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q2,5 PRO (320*160), outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 128.0,
      "cabinetHeightMm": 64.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.42,
      "priceUsd": 39.2,
      "priceRub": null
    },
    {
      "id": "qiangli-q3-07-pro-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q3,07 PRO (320*160), outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 104.0,
      "cabinetHeightMm": 52.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.4,
      "priceUsd": 23.3,
      "priceRub": null
    },
    {
      "id": "qiangli-q3-07-eco-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q3,07 ECO (320*160), outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 104.0,
      "cabinetHeightMm": 52.0,
      "modulesWide": 1920.0,
      "modulesTall": 10.0,
      "weightKg": 0.4,
      "priceUsd": 21.0,
      "priceRub": null
    },
    {
      "id": "qiangli-q4-pro-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q4-PRO (320*160),outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 80.0,
      "cabinetHeightMm": 40.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.52,
      "priceUsd": 16.2,
      "priceRub": null
    },
    {
      "id": "qiangli-q4-eco-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q4-ECO (320*160),outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 80.0,
      "cabinetHeightMm": 40.0,
      "modulesWide": 1920.0,
      "modulesTall": 10.0,
      "weightKg": 0.55,
      "priceUsd": 15.2,
      "priceRub": null
    },
    {
      "id": "qiangli-q5-pro-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q5 PRO (320*160), outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 64.0,
      "cabinetHeightMm": 32.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.49,
      "priceUsd": 13.5,
      "priceRub": null
    },
    {
      "id": "qiangli-q5-eco-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q5 ECO (320*160), outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 64.0,
      "cabinetHeightMm": 32.0,
      "modulesWide": 1920.0,
      "modulesTall": 10.0,
      "weightKg": 0.45,
      "priceUsd": 12.5,
      "priceRub": null
    },
    {
      "id": "qiangli-q5-pro-320-160-outdoor-soft-mask-soft-mask",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q5-Pro (320*160),outdoor soft mask",
      "execution": "Уличный",
      "service": "Soft mask",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 64.0,
      "cabinetHeightMm": 32.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.49,
      "priceUsd": 24.799978856115867,
      "priceRub": null
    },
    {
      "id": "qiangli-q5-eco-320-160-outdoor-soft-mask-soft-mask",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q5-Eco (320*160),outdoor soft mask",
      "execution": "Уличный",
      "service": "Soft mask",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 64.0,
      "cabinetHeightMm": 32.0,
      "modulesWide": 1920.0,
      "modulesTall": 10.0,
      "weightKg": 0.45,
      "priceUsd": 22.0,
      "priceRub": null
    },
    {
      "id": "qiangli-q6-192-192-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q6 (192*192), outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 192.0,
      "cabinetWidthMm": 32.0,
      "cabinetHeightMm": 32.0,
      "modulesWide": 3840.0,
      "modulesTall": 9.0,
      "weightKg": 0.32,
      "priceUsd": 9.5,
      "priceRub": null
    },
    {
      "id": "qiangli-q6-66-pro-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q6,66 PRO (320*160), outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 48.0,
      "cabinetHeightMm": 24.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.51,
      "priceUsd": 13.0,
      "priceRub": null
    },
    {
      "id": "qiangli-q6-66-eco-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q6,66 ECO (320*160), outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 48.0,
      "cabinetHeightMm": 24.0,
      "modulesWide": 1920.0,
      "modulesTall": 10.0,
      "weightKg": 0.51,
      "priceUsd": 12.1,
      "priceRub": null
    },
    {
      "id": "qiangli-q6-66-pro-320-160-outdoor-soft-mask-soft-mask",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q6,66-Pro (320*160),outdoor soft mask",
      "execution": "Уличный",
      "service": "Soft mask",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 48.0,
      "cabinetHeightMm": 24.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.51,
      "priceUsd": 29.200021143884133,
      "priceRub": null
    },
    {
      "id": "qiangli-q8-pro-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q8-PRO (320*160),outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 40.0,
      "cabinetHeightMm": 20.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.48,
      "priceUsd": 12.6,
      "priceRub": null
    },
    {
      "id": "qiangli-q8-eco-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q8-ECO (320*160),outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 40.0,
      "cabinetHeightMm": 20.0,
      "modulesWide": 1920.0,
      "modulesTall": 10.0,
      "weightKg": 0.48,
      "priceUsd": 11.8,
      "priceRub": null
    },
    {
      "id": "qiangli-q8-pro-320-160-outdoor-soft-mask-soft-mask",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q8-Pro (320*160),outdoor soft mask",
      "execution": "Уличный",
      "service": "Soft mask",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 40.0,
      "cabinetHeightMm": 20.0,
      "modulesWide": 3840.0,
      "modulesTall": 10.0,
      "weightKg": 0.48,
      "priceUsd": 19.2,
      "priceRub": null
    },
    {
      "id": "qiangli-q8-eco-320-160-outdoor-soft-mask-soft-mask",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q8-Eco (320*160), outdoor soft mask",
      "execution": "Уличный",
      "service": "Soft mask",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 40.0,
      "cabinetHeightMm": 20.0,
      "modulesWide": 1920.0,
      "modulesTall": 10.0,
      "weightKg": 0.48,
      "priceUsd": 17.0,
      "priceRub": null
    },
    {
      "id": "qiangli-q10-320-160-outdoor-smd",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, Q10-(320*160),outdoor",
      "execution": "Уличный",
      "service": "SMD",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 32.0,
      "cabinetHeightMm": 16.0,
      "modulesWide": 1920.0,
      "modulesTall": 10.0,
      "weightKg": 0.48,
      "priceUsd": 22.0,
      "priceRub": null
    },
    {
      "id": "qiangli-s10-320-160-7680-hz-outdoor-gold-smd-gold",
      "manufacturer": "",
      "sku": null,
      "name": "QIANGLI, S10 (320*160) 7680 hz,outdoor,gold",
      "execution": "Уличный",
      "service": "SMD gold",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 32.0,
      "cabinetHeightMm": 16.0,
      "modulesWide": 7680.0,
      "modulesTall": 10.0,
      "weightKg": 0.48,
      "priceUsd": 15.83,
      "priceRub": null
    },
    {
      "id": "qiangli-smgobip-125320160-gob",
      "manufacturer": "QIANGLI",
      "sku": "SMGOBIP-125320160",
      "name": "QIANGLI, Q1,25 GOB (320*160) 6000 hz,indoor",
      "execution": "Внутренний",
      "service": "GOB",
      "moduleWidthMm": 320.0,
      "cabinetWidthMm": 256.0,
      "cabinetHeightMm": 128.0,
      "modulesWide": 6000.0,
      "modulesTall": 12.0,
      "weightKg": 0.58,
      "priceUsd": 78.66,
      "priceRub": null
    }
  ],
  "modules": [
    {
      "id": "qiangli-q0-8-pro-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q0,8-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 0.8,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 360.0,
        "height": 180.0
      },
      "signal": "HUB320",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.5,
      "maxCurrentA": 8.0,
      "maxPowerWPerM2": 703.0,
      "avgPowerWPerM2": 235.0,
      "brightnessNits": 600.0,
      "priceUsd": 815.0000000000001
    },
    {
      "id": "qiangli-q1-pro-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q1-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 1.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 320.0,
        "height": 160.0
      },
      "signal": "HUB320",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.5,
      "maxCurrentA": 9.0,
      "maxPowerWPerM2": 791.0,
      "avgPowerWPerM2": 264.0,
      "brightnessNits": 600.0,
      "priceUsd": 450.0
    },
    {
      "id": "qiangli-q1-25-pro-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q1,25-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 1.25,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 256.0,
        "height": 128.0
      },
      "signal": "HUB320",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.52,
      "maxCurrentA": 6.6,
      "maxPowerWPerM2": 580.0,
      "avgPowerWPerM2": 194.0,
      "brightnessNits": 600.0,
      "priceUsd": 70.0
    },
    {
      "id": "qiangli-q1-37-pro-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q1,37-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 1.37,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 232.0,
        "height": 116.0
      },
      "signal": "HUB320",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.47,
      "maxCurrentA": 6.6,
      "maxPowerWPerM2": 580.0,
      "avgPowerWPerM2": 194.0,
      "brightnessNits": 600.0,
      "priceUsd": 81.0
    },
    {
      "id": "qiangli-q1-53-rgb-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q1,53-RGB (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 1.53,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 208.0,
        "height": 104.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.47,
      "maxCurrentA": 6.6,
      "maxPowerWPerM2": 580.0,
      "avgPowerWPerM2": 194.0,
      "brightnessNits": 600.0,
      "priceUsd": 41.8
    },
    {
      "id": "qiangli-q1-66-pro-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q1,66-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 1.66,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 192.0,
        "height": 96.0
      },
      "signal": "HUB320",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.4,
      "maxCurrentA": 6.6,
      "maxPowerWPerM2": 580.0,
      "avgPowerWPerM2": 194.0,
      "brightnessNits": 600.0,
      "priceUsd": 42.2
    },
    {
      "id": "qiangli-q1-86-pro-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q1,86-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 1.86,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 172.0,
        "height": 86.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.37,
      "maxCurrentA": 5.0,
      "maxPowerWPerM2": 439.0,
      "avgPowerWPerM2": 147.0,
      "brightnessNits": 600.0,
      "priceUsd": 26.8
    },
    {
      "id": "qiangli-q1-86-eco-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q1,86-ECO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 1.86,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 172.0,
        "height": 86.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 12.0,
      "weightKg": 0.37,
      "maxCurrentA": 5.0,
      "maxPowerWPerM2": 439.0,
      "avgPowerWPerM2": 147.0,
      "brightnessNits": 500.0,
      "priceUsd": 25.2
    },
    {
      "id": "qiangli-q2-pro-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q2-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 2.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 160.0,
        "height": 80.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.37,
      "maxCurrentA": 5.0,
      "maxPowerWPerM2": 439.0,
      "avgPowerWPerM2": 147.0,
      "brightnessNits": 600.0,
      "priceUsd": 23.8
    },
    {
      "id": "qiangli-q2-eco-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q2-ECO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 2.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 160.0,
        "height": 80.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 12.0,
      "weightKg": 0.37,
      "maxCurrentA": 5.0,
      "maxPowerWPerM2": 457.0,
      "avgPowerWPerM2": 153.0,
      "brightnessNits": 500.0,
      "priceUsd": 22.25
    },
    {
      "id": "qiangli-q2-5-pro-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q2,5-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 2.5,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 128.0,
        "height": 64.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.37,
      "maxCurrentA": 5.2,
      "maxPowerWPerM2": 457.0,
      "avgPowerWPerM2": 153.0,
      "brightnessNits": 600.0,
      "priceUsd": 17.15
    },
    {
      "id": "qiangli-q2-5-eco-320-160-indoor",
      "series": "Q-series",
      "manufacturer": "",
      "sku": "",
      "name": "QIANGLI, Q2,5-ECO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 2.5,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 128.0,
        "height": 64.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 12.0,
      "weightKg": 0.37,
      "maxCurrentA": 5.2,
      "maxPowerWPerM2": 457.0,
      "avgPowerWPerM2": 153.0,
      "brightnessNits": 500.0,
      "priceUsd": 15.3
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "Светодиодный модуль QIANGLI, DM2,6 (250*250) 6000 hz,indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 2.6,
      "sizeMm": {
        "width": 250.0,
        "height": 250.0
      },
      "pixels": {
        "width": 96.0,
        "height": 96.0
      },
      "signal": "HUB75",
      "refreshRateHz": 6000.0,
      "mountPoints": 10.0,
      "weightKg": 0.5,
      "maxCurrentA": 8.0,
      "maxPowerWPerM2": 432.0,
      "avgPowerWPerM2": 144.0,
      "brightnessNits": 600.0,
      "priceUsd": 25.2
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q3-PRO (192*192),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 3.0,
      "sizeMm": {
        "width": 192.0,
        "height": 192.0
      },
      "pixels": {
        "width": 64.0,
        "height": 64.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 9.0,
      "weightKg": 0.28,
      "maxCurrentA": 4.3,
      "maxPowerWPerM2": 525.0,
      "avgPowerWPerM2": 175.0,
      "brightnessNits": 600.0,
      "priceUsd": 12.4
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q3-ECO (192*192),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 3.0,
      "sizeMm": {
        "width": 192.0,
        "height": 192.0
      },
      "pixels": {
        "width": 64.0,
        "height": 64.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 9.0,
      "weightKg": 0.28,
      "maxCurrentA": 4.3,
      "maxPowerWPerM2": 525.0,
      "avgPowerWPerM2": 175.0,
      "brightnessNits": 500.0,
      "priceUsd": 10.2
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q3,07-PRO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 3.07,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 104.0,
        "height": 52.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.32,
      "maxCurrentA": 4.7,
      "maxPowerWPerM2": 413.0,
      "avgPowerWPerM2": 138.0,
      "brightnessNits": 600.0,
      "priceUsd": 13.5
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q3,07-ECO (320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 3.07,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 104.0,
        "height": 52.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 12.0,
      "weightKg": 0.32,
      "maxCurrentA": 4.7,
      "maxPowerWPerM2": 413.0,
      "avgPowerWPerM2": 138.0,
      "brightnessNits": 500.0,
      "priceUsd": 12.3
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q4-PRO(320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 4.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 80.0,
        "height": 40.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 12.0,
      "weightKg": 0.35,
      "maxCurrentA": 5.3,
      "maxPowerWPerM2": 465.0,
      "avgPowerWPerM2": 155.0,
      "brightnessNits": 600.0,
      "priceUsd": 10.9
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q4-ECO(320*160),indoor",
      "execution": "Внутренний",
      "technology": "SMD",
      "pixelPitchMm": 4.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 80.0,
        "height": 40.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 12.0,
      "weightKg": 0.35,
      "maxCurrentA": 5.3,
      "maxPowerWPerM2": 465.0,
      "avgPowerWPerM2": 155.0,
      "brightnessNits": 500.0,
      "priceUsd": 9.9
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q2,5 PRO (320*160), outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 2.5,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 128.0,
        "height": 64.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.42,
      "maxCurrentA": 7.37,
      "maxPowerWPerM2": 648.0,
      "avgPowerWPerM2": 216.0,
      "brightnessNits": 4500.0,
      "priceUsd": 39.2
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q3,07 PRO (320*160), outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 3.07,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 104.0,
        "height": 52.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.4,
      "maxCurrentA": 8.94,
      "maxPowerWPerM2": 786.0,
      "avgPowerWPerM2": 262.0,
      "brightnessNits": 5000.0,
      "priceUsd": 23.3
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q3,07 ECO (320*160), outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 3.07,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 104.0,
        "height": 52.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 10.0,
      "weightKg": 0.4,
      "maxCurrentA": 8.94,
      "maxPowerWPerM2": 786.0,
      "avgPowerWPerM2": 262.0,
      "brightnessNits": 5000.0,
      "priceUsd": 21.0
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q4-PRO (320*160),outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 4.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 80.0,
        "height": 40.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.52,
      "maxCurrentA": 10.34,
      "maxPowerWPerM2": 909.0,
      "avgPowerWPerM2": 303.0,
      "brightnessNits": 5500.0,
      "priceUsd": 16.2
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q4-ECO (320*160),outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 4.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 80.0,
        "height": 40.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 10.0,
      "weightKg": 0.55,
      "maxCurrentA": 10.34,
      "maxPowerWPerM2": 909.0,
      "avgPowerWPerM2": 303.0,
      "brightnessNits": 5500.0,
      "priceUsd": 15.2
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q5 PRO (320*160), outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 5.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 64.0,
        "height": 32.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.49,
      "maxCurrentA": 9.51,
      "maxPowerWPerM2": 836.0,
      "avgPowerWPerM2": 279.0,
      "brightnessNits": 5500.0,
      "priceUsd": 13.5
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q5 ECO (320*160), outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 5.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 64.0,
        "height": 32.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 10.0,
      "weightKg": 0.45,
      "maxCurrentA": 9.51,
      "maxPowerWPerM2": 836.0,
      "avgPowerWPerM2": 279.0,
      "brightnessNits": 5500.0,
      "priceUsd": 12.5
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q5-Pro (320*160),outdoor soft mask",
      "execution": "Уличный",
      "technology": "Soft mask",
      "pixelPitchMm": 5.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 64.0,
        "height": 32.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.49,
      "maxCurrentA": 9.51,
      "maxPowerWPerM2": 836.0,
      "avgPowerWPerM2": 279.0,
      "brightnessNits": 5500.0,
      "priceUsd": 24.799978856115867
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q5-Eco (320*160),outdoor soft mask",
      "execution": "Уличный",
      "technology": "Soft mask",
      "pixelPitchMm": 5.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 64.0,
        "height": 32.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 10.0,
      "weightKg": 0.45,
      "maxCurrentA": 9.51,
      "maxPowerWPerM2": 836.0,
      "avgPowerWPerM2": 279.0,
      "brightnessNits": 5500.0,
      "priceUsd": 22.0
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q6 (192*192), outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 6.0,
      "sizeMm": {
        "width": 192.0,
        "height": 192.0
      },
      "pixels": {
        "width": 32.0,
        "height": 32.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 9.0,
      "weightKg": 0.32,
      "maxCurrentA": 7.75,
      "maxPowerWPerM2": 946.0,
      "avgPowerWPerM2": 315.0,
      "brightnessNits": 5000.0,
      "priceUsd": 9.5
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q6,66 PRO (320*160), outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 6.66,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 48.0,
        "height": 24.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.51,
      "maxCurrentA": 10.15,
      "maxPowerWPerM2": 892.0,
      "avgPowerWPerM2": 297.0,
      "brightnessNits": 5500.0,
      "priceUsd": 13.0
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q6,66 ECO (320*160), outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 6.66,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 48.0,
        "height": 24.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 10.0,
      "weightKg": 0.51,
      "maxCurrentA": 10.15,
      "maxPowerWPerM2": 892.0,
      "avgPowerWPerM2": 297.0,
      "brightnessNits": 5500.0,
      "priceUsd": 12.1
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q6,66-Pro (320*160),outdoor soft mask",
      "execution": "Уличный",
      "technology": "Soft mask",
      "pixelPitchMm": 6.66,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 48.0,
        "height": 24.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.51,
      "maxCurrentA": 10.15,
      "maxPowerWPerM2": 892.0,
      "avgPowerWPerM2": 297.0,
      "brightnessNits": 5500.0,
      "priceUsd": 29.200021143884133
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q8-PRO (320*160),outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 8.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 40.0,
        "height": 20.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.48,
      "maxCurrentA": 9.85,
      "maxPowerWPerM2": 866.0,
      "avgPowerWPerM2": 289.0,
      "brightnessNits": 5500.0,
      "priceUsd": 12.6
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q8-ECO (320*160),outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 8.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 40.0,
        "height": 20.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 10.0,
      "weightKg": 0.48,
      "maxCurrentA": 9.85,
      "maxPowerWPerM2": 866.0,
      "avgPowerWPerM2": 289.0,
      "brightnessNits": 5500.0,
      "priceUsd": 11.8
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q8-Pro (320*160),outdoor soft mask",
      "execution": "Уличный",
      "technology": "Soft mask",
      "pixelPitchMm": 8.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 40.0,
        "height": 20.0
      },
      "signal": "HUB75",
      "refreshRateHz": 3840.0,
      "mountPoints": 10.0,
      "weightKg": 0.48,
      "maxCurrentA": 9.85,
      "maxPowerWPerM2": 866.0,
      "avgPowerWPerM2": 289.0,
      "brightnessNits": 5500.0,
      "priceUsd": 19.2
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q8-Eco (320*160), outdoor soft mask",
      "execution": "Уличный",
      "technology": "Soft mask",
      "pixelPitchMm": 8.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 40.0,
        "height": 20.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 10.0,
      "weightKg": 0.48,
      "maxCurrentA": 9.85,
      "maxPowerWPerM2": 866.0,
      "avgPowerWPerM2": 289.0,
      "brightnessNits": 5500.0,
      "priceUsd": 17.0
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, Q10-(320*160),outdoor",
      "execution": "Уличный",
      "technology": "SMD",
      "pixelPitchMm": 10.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 32.0,
        "height": 16.0
      },
      "signal": "HUB75",
      "refreshRateHz": 1920.0,
      "mountPoints": 10.0,
      "weightKg": 0.48,
      "maxCurrentA": 9.75,
      "maxPowerWPerM2": 857.0,
      "avgPowerWPerM2": 286.0,
      "brightnessNits": 6000.0,
      "priceUsd": 22.0
    },
    {
      "id": "smdmi-q26250250",
      "series": "Q-series",
      "manufacturer": "Qiangli",
      "sku": "SMDMI-Q26250250",
      "name": "QIANGLI, S10 (320*160) 7680 hz,outdoor,gold",
      "execution": "Уличный",
      "technology": "SMD gold",
      "pixelPitchMm": 10.0,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 32.0,
        "height": 16.0
      },
      "signal": "HUB75",
      "refreshRateHz": 7680.0,
      "mountPoints": 10.0,
      "weightKg": 0.48,
      "maxCurrentA": 9.75,
      "maxPowerWPerM2": 857.0,
      "avgPowerWPerM2": 286.0,
      "brightnessNits": 6000.0,
      "priceUsd": 15.83
    },
    {
      "id": "smgobip-125320160",
      "series": "Q-series",
      "manufacturer": "QIANGLI",
      "sku": "SMGOBIP-125320160",
      "name": "QIANGLI, Q1,25 GOB (320*160) 6000 hz,indoor",
      "execution": "Внутренний",
      "technology": "GOB",
      "pixelPitchMm": 1.25,
      "sizeMm": {
        "width": 320.0,
        "height": 160.0
      },
      "pixels": {
        "width": 256.0,
        "height": 128.0
      },
      "signal": "HUB320",
      "refreshRateHz": 6000.0,
      "mountPoints": 12.0,
      "weightKg": 0.58,
      "maxCurrentA": 6.6,
      "maxPowerWPerM2": 580.0,
      "avgPowerWPerM2": 192.0,
      "brightnessNits": 650.0,
      "priceUsd": 78.66
    }
  ],
  "receivingCards": [
    {
      "id": "novastar-mrv-208",
      "name": "Контроллер Novastar MRV 208",
      "type": "Принимающая карта",
      "requiresHub": false,
      "connectorCount": 8.0,
      "maxPixels": {
        "width": 256.0,
        "height": 256.0
      },
      "signal": "HUB75",
      "weightKg": 0.075,
      "priceUsd": 15.0
    },
    {
      "id": "novastar-mrv-416",
      "name": "Контроллер Novastar MRV 416",
      "type": "Принимающая карта",
      "requiresHub": false,
      "connectorCount": 16.0,
      "maxPixels": {
        "width": 512.0,
        "height": 384.0
      },
      "signal": "HUB75",
      "weightKg": 0.125,
      "priceUsd": 18.9
    },
    {
      "id": "novastar-mrv-412",
      "name": "Контроллер Novastar MRV 412",
      "type": "Принимающая карта",
      "requiresHub": false,
      "connectorCount": 12.0,
      "maxPixels": {
        "width": 512.0,
        "height": 512.0
      },
      "signal": "HUB75",
      "weightKg": 0.125,
      "priceUsd": 18.5
    },
    {
      "id": "novastar-a5s-plus",
      "name": "Контроллер Novastar A5s Plus",
      "type": "Контроллер",
      "requiresHub": true,
      "connectorCount": 8.0,
      "maxPixels": {
        "width": 512.0,
        "height": 384.0
      },
      "signal": "HUB320",
      "weightKg": 0.366,
      "priceUsd": 17.0
    },
    {
      "id": "novastar-a10s-plus",
      "name": "Контроллер Novastar A10s Plus",
      "type": "Контроллер",
      "requiresHub": true,
      "connectorCount": 8.0,
      "maxPixels": {
        "width": 512.0,
        "height": 512.0
      },
      "signal": "HUB320",
      "weightKg": 0.366,
      "priceUsd": 46.0
    }
  ],
  "controllers": [
    {
      "id": "novastar-mctrl-300",
      "name": "Novastar MCTRL 300",
      "deviceType": "Контроллер",
      "scaling": "Без масштабирования",
      "portCount": 2.0,
      "throughputPerPort": 650000.0,
      "aggregateThroughput": 2104320.0,
      "maxPixels": {
        "width": 3840.0,
        "height": 3840.0
      },
      "priceUsd": 161.0
    },
    {
      "id": "novastar-mctrl-600",
      "name": "Novastar MCTRL 600",
      "deviceType": "Контроллер",
      "scaling": "Без масштабирования",
      "portCount": 4.0,
      "throughputPerPort": 650000.0,
      "aggregateThroughput": 2104320.0,
      "maxPixels": {
        "width": 3840.0,
        "height": 3840.0
      },
      "priceUsd": 294.0
    },
    {
      "id": "novastar-m-trl-700",
      "name": "Novastar MСTRL 700",
      "deviceType": "Контроллер",
      "scaling": "Без масштабирования",
      "portCount": 6.0,
      "throughputPerPort": 650000.0,
      "aggregateThroughput": 2104320.0,
      "maxPixels": {
        "width": 3840.0,
        "height": 3840.0
      },
      "priceUsd": 307.0
    },
    {
      "id": "novastar-vx400s-n",
      "name": "Novastar VX400S-N",
      "deviceType": "Видеопроцессор",
      "scaling": "С масштабированием",
      "portCount": 4.0,
      "throughputPerPort": 650000.0,
      "aggregateThroughput": 2600000.0,
      "maxPixels": {
        "width": 10240.0,
        "height": 8192.0
      },
      "priceUsd": 520.0
    },
    {
      "id": "novastar-vx400",
      "name": "Novastar VX400",
      "deviceType": "Видеопроцессор",
      "scaling": "С масштабированием",
      "portCount": 4.0,
      "throughputPerPort": 650000.0,
      "aggregateThroughput": 2600000.0,
      "maxPixels": {
        "width": 10240.0,
        "height": 8192.0
      },
      "priceUsd": 926.0
    },
    {
      "id": "novastar-vx600",
      "name": "Novastar VX600",
      "deviceType": "Видеопроцессор",
      "scaling": "С масштабированием",
      "portCount": 6.0,
      "throughputPerPort": 650000.0,
      "aggregateThroughput": 3900000.0,
      "maxPixels": {
        "width": 10240.0,
        "height": 8192.0
      },
      "priceUsd": 1100.0
    },
    {
      "id": "novastar-vx1000",
      "name": "Novastar VX1000",
      "deviceType": "Видеопроцессор",
      "scaling": "С масштабированием",
      "portCount": 10.0,
      "throughputPerPort": 650000.0,
      "aggregateThroughput": 6500000.0,
      "maxPixels": {
        "width": 10240.0,
        "height": 8192.0
      },
      "priceUsd": 1590.0
    },
    {
      "id": "novastar-vx16s",
      "name": "Novastar VX16S",
      "deviceType": "Видеопроцессор",
      "scaling": "С масштабированием",
      "portCount": 16.0,
      "throughputPerPort": 650000.0,
      "aggregateThroughput": 10400000.0,
      "maxPixels": {
        "width": 16384.0,
        "height": 8192.0
      },
      "priceUsd": 2920.0
    }
  ],
  "hubs": [
    {
      "id": "hub-320-axs",
      "name": "Плата HUB 320-AXS",
      "type": "Хаб",
      "connectorCount": 8.0,
      "signal": "HUB320",
      "priceUsd": 15.0
    }
  ],
  "powerSupplies": [
    {
      "id": "a-200af-4-5-slim",
      "name": "Блок питания A-200AF 4,5 slim",
      "powerW": 200.0,
      "currentA": 40.0,
      "weightKg": 0.56,
      "priceUsd": 8.0
    },
    {
      "id": "a-300fay-4-5",
      "name": "Блок питания A-300FAY 4,5",
      "powerW": 300.0,
      "currentA": 60.0,
      "weightKg": 0.56,
      "priceUsd": 15.4
    },
    {
      "id": "a-350a-4-5-slim",
      "name": "Блок питания A-350AК-4,5 slim",
      "powerW": 350.0,
      "currentA": 70.0,
      "weightKg": 0.56,
      "priceUsd": 16.2
    },
    {
      "id": "a-400ak-4-5-slim",
      "name": "Блок питания A-400AK 4,5 Slim",
      "powerW": 400.0,
      "currentA": 80.0,
      "weightKg": 0.56,
      "priceUsd": 17.3
    }
  ],
  "accessories": [
    {
      "id": "4-12",
      "name": "Винт М4*12",
      "category": "Крепеж",
      "service": "Тыльное",
      "signal": null,
      "priceUsd": 0.05
    },
    {
      "id": "12-8-1-2",
      "name": "Магнит 12*8*1,2",
      "category": "Крепеж",
      "service": "Фронтальное",
      "signal": null,
      "priceUsd": 0.08
    },
    {
      "id": "16-pin",
      "name": "Коннектор 16 PIN",
      "category": "Коннектор",
      "service": null,
      "signal": "HUB75",
      "priceUsd": 0.09
    },
    {
      "id": "26-pin",
      "name": "Коннектор 26 PIN",
      "category": "Коннектор",
      "service": null,
      "signal": "HUB320",
      "priceUsd": 0.18
    },
    {
      "id": "16-pin-75",
      "name": "Шлейф бухта 16 PIN, 75 м",
      "category": "Шлейф",
      "service": null,
      "signal": "HUB75",
      "priceUsd": 25.0
    },
    {
      "id": "26-pin-75",
      "name": "Шлейф бухта 26 PIN, 75 м",
      "category": "Шлейф",
      "service": null,
      "signal": "HUB320",
      "priceUsd": 50.0
    }
  ]
};
